"""
Django settings for appBeerPub project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$9!t7$46)z9uxwyyzh86$ecsfaf3ak)n-_v@g2n=#2y#zcre)t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# averiguar que es??
ALLOWED_HOSTS = []
#segun lei es una proteccion para habilitar quien puede acceder a la app
# ALLOWED_HOSTS = [
#   'localhost',
#   '127.0.0.1'
#    ]


# Application definition

CUSTOM_APP=[
        'beerpub',
        'django_bootstrap5', 
        'widget_tweaks', 
        ]

EXTERNALS = [
    "rest_framework"
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
INSTALLED_APPS += CUSTOM_APP
INSTALLED_APPS += EXTERNALS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'appBeerPub.urls'

#me faltaba esto         'DIRS': [BASE_DIR / "templates"],
# lo cambie por         'DIRS': [],
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'appBeerPub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'leogabii$beerpub',
        'USER': 'leogabii',
        'PASSWORD': 'comision23507',
        'HOST': 'leogabii.mysql.pythonanywhere-services.com',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

#STATIC_URL = 'static/'

#---------------------------------------------------------------
#agregado porque esta en la explicacion del profe, investigar

# STATICFILES_DIRS = [
#     BASE_DIR / "static"]

#---------------------------------------------------------------

# La URL para los archivos Estáticos (CSS, JS, Imágenes, etc.)
STATIC_URL = '/static/' 

# Las rutas para las imágenes de cada registro
MEDIA_URL = '/beerpub/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'beerpub/static/uploads')

# ----------------------probando alternativas--------------------------
# Las rutas para las imágenes de cada registro
#MEDIA_URL = '/beerpub/img/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'beerpub/static')

#----------------------------------------------------------------------

# Activamos 'CookieStorage' que nos permite enviar los mensajes de respuesta al Crear, Eliminar y Actualizar un registro
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
